services:
  mysql:
    image: mysql:8.0
    container_name: author-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: author_db
      MYSQL_USER: author_user
      MYSQL_PASSWORD: author_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  author-service:
    build: .
    container_name: author-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: author-service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/author_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: author_user
      SPRING_DATASOURCE_PASSWORD: author_pass
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  mysql_data:
